from __future__ import annotations

import os
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageOps

SOURCE = Path(os.environ["VIQUEVIET_ASSET_SOURCE"])
ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".avif"}

PRODUCT_ROOT = SOURCE / "Ảnh sản phẩm Vị Quê Việt"
COMMON = PRODUCT_ROOT / "Món chung"
FACTORY = SOURCE / "Nhà máy sản xuất" / "Nhà xưởng" / "Med"

PRODUCTS = {
    "ruoc-ca-hoi": PRODUCT_ROOT / "Ruốc cá hồi" / "LD18.9-02.jpg",
    "xuc-xich-gac": COMMON / "11.6.2-05.jpg",
    "xuc-xich-ga-nam": COMMON / "11.6.2-22.jpg",
    "xuc-xich": COMMON / "11.6.2-23.jpg",
    "cha-uc-ga-healthy": COMMON / "11.6.2-12.jpg",
    "pate-ha-noi": COMMON / "28.5-07.jpg",
    "nem-chua-ran": COMMON / "11.6.2-04.jpg",
    "lap-xuong": COMMON / "11.6.2-03.jpg",
    "gio-xao": COMMON / "11.6.2-08.jpg",
    "gio-lua": COMMON / "11.6.2-10.jpg",
    "gio-bo": COMMON / "11.6.2-09.jpg",
    "gio-bi": COMMON / "11.6.2-06.jpg",
    "ga-u-muoi": COMMON / "11.6.2-24.jpg",
    "doi-sun": COMMON / "11.6.2-11.jpg",
    "cha-sun": COMMON / "11.6.2-07.jpg",
    "cha-oc": COMMON / "11.6.2-21.jpg",
    "cha-com-tu-le": COMMON / "11.6.2-25.jpg",
}

SUPPORTING = {
    "brand/hero-products.webp": (COMMON / "18.7-01.jpg", 1600),
    "brand/brand-story.webp": (COMMON / "16.7.2-01.jpg", 1200),
    "factory/factory-hero.webp": (FACTORY / "28.05.25 7.jpg", 1600),
    "factory/production-line.webp": (FACTORY / "LINH DANG FOOD-08.jpg", 1200),
    "factory/quality-control.webp": (FACTORY / "sửa bài 12.6-11.jpg", 1200),
    "factory/workers.webp": (FACTORY / "29.7-05.jpg", 1200),
    "factory/equipment.webp": (FACTORY / "LD8.9-04.jpg", 1200),
    "oem/oem-process.webp": (FACTORY / "LD6.9-01.jpg", 1200),
    "news/quy-trinh-san-xuat.webp": (FACTORY / "sửa bài 12.6-13.jpg", 1000),
    "news/nguyen-lieu-sach.webp": (SOURCE / "Ảnh sản phẩm Vị Quê Việt" / "Giò Chả" / "QUẢNG CÁO 6.6-05.jpg", 1000),
    "news/nem-chua-ran.webp": (PRODUCT_ROOT / "Nem chua rán" / "14.7-01.jpg", 1000),
}


def optimize(source: Path, destination: Path, max_width: int) -> None:
    if not source.exists():
        raise FileNotFoundError(source)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(source) as image:
        image = ImageOps.exif_transpose(image).convert("RGB")
        if image.width > max_width:
            height = round(image.height * max_width / image.width)
            image = image.resize((max_width, height), Image.Resampling.LANCZOS)
        image.save(destination, "WEBP", quality=82, method=6)


selected: dict[Path, list[str]] = {}

for slug, source in PRODUCTS.items():
    for name, width in (("card.webp", 800), ("hero.webp", 1400)):
        destination = PUBLIC / "images" / "products" / slug / name
        optimize(source, destination, width)
        selected.setdefault(source.resolve(), []).append(destination.relative_to(ROOT).as_posix())

for relative, (source, width) in SUPPORTING.items():
    destination = PUBLIC / "images" / relative
    optimize(source, destination, width)
    selected.setdefault(source.resolve(), []).append(destination.relative_to(ROOT).as_posix())


def category_for(path: Path) -> str:
    relative = path.relative_to(SOURCE).as_posix().lower()
    if "ảnh sản phẩm" in relative:
        return "products"
    if "nhà máy" in relative:
        return "factory"
    if "quảng bá" in relative:
        return "news"
    return "other"


all_assets: Iterable[Path] = sorted(
    path for path in SOURCE.rglob("*") if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
)
rows = [
    "# Asset inventory",
    "",
    "> Generated by `scripts/migrate-assets.py`. Original media is read-only; only selected assets are copied and optimized.",
    "",
    "| Original file | Category | Suggested usage | New filename | New project path | Status |",
    "|---|---|---|---|---|---|",
]
for asset in all_assets:
    destinations = selected.get(asset.resolve(), [])
    if destinations:
        new_paths = "<br>".join(destinations)
        new_names = "<br>".join(Path(item).name for item in destinations)
        usage = "Production website image"
        status = "Migrated and optimized"
    else:
        new_paths = "—"
        new_names = "—"
        usage = "Source archive / future content"
        status = "Reviewed, not selected for MVP"
    original = asset.relative_to(SOURCE).as_posix().replace("|", "\\|")
    rows.append(f"| `{original}` | {category_for(asset)} | {usage} | `{new_names}` | `{new_paths}` | {status} |")

docs = ROOT / "docs"
docs.mkdir(exist_ok=True)
(docs / "assets-inventory.md").write_text("\n".join(rows) + "\n", encoding="utf-8")
print(f"Migrated {sum(len(value) for value in selected.values())} image variants from {len(selected)} source assets.")
print(f"Inventoried {len(rows) - 6} source images.")
